name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to cPanel via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTP_HOST }} # Host FTP
        username: ${{ secrets.FTP_USERNAME }} # Username FTP
        password: ${{ secrets.FTP_PASSWORD }} # Password FTP
        port: 21 # Porta FTP (di default è 21, puoi personalizzarla)
        protocol: ftp # Protocollo FTP
        local-dir: ./ # Cartella locale con i file da caricare
        server-dir: / # Cartella sul server dove caricare i file